api:
  dashboard: false
log:
  level: INFO #DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
global:
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik_bridge"
    watch: true
  file:
    directory: /etc/traefik/dynamic/
    watch: true

entryPoints:
  http:
    address: :80
  https:
    address: :443

certificatesResolvers:
  default:
    acme:
      email: sample@mail.com
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: http
